POST http://localhost:3000/user
Content-Type: application/json

{
    "nome": "nicolas",
    "email": "nicolas@hotmail.com",
    "senha": "marcel123",
    "telefone": "67992336868",
    "cpf": "22.000.000-00"
}
###

GET http://localhost:3000/user
###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "marcel@hotmail.com",
    "senha": "marcel123"
}
