POST http://localhost:3030/user
Content-Type: application/json

{
    "nome": "marcel",
    "email": "test@hotmail.com",
    "senha": "marcel123",
    "telefone": "67992336868",
    "cpf": "008.000.000-00"
}
###

GET http://localhost:3030/user
###


POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "email": "marcel@hotmail.com",
    "senha": "marcel123"
}
